spring:
  profiles:
    active: prod
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          open-in-view: false
          use_sql_comments: true
          type:
            resolver: org.hibernate.type.BasicTypeResolverStandardImpl
          dialect: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
mvc:
  path-match:
    matching-strategy: ant_path_matcher

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /docs/swagger

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-exp-time: ${JWT_ACCESS_EXP_TIME}
  refresh-exp-time: ${JWT_REFRESH_EXP_TIME}

cloud:
  aws:
    s3:
      bucket: sul-game-media
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

fcm:
  firebase_config_path: firebase/sul-game-firebase-adminsdk.json